language: node_js
node_js:
  - "stable"
cache:
  yarn: true
  directories:
    - node_modules
install:
  - yarn global add codecov
  - yarn
jobs:
  include:
    - stage: Build and test
      script:
        - lint-staged
        - yarn test:ci && codecov
        - yarn build
    - stage: npm release
      script: yarn build
      deploy:
        - provider: releases
          api_key: $GH_TOKEN
          file_glob: true
          file: "dist/*/**"
          skip_cleanup: true
          on:
            tags: true
        - provider: npm
          email: "fifthsage@gmail.com"
          api_key: "$NPM_TOKEN"
          skip_cleanup: true
          on:
            tags: true
            repo: fifthsage/react_amplitude
branches:
  only:
    - master
    - /^v[0-9]+.*$/
