language: node_js
node_js:
  - "stable"
cache:
  yarn: true
  directories:
    - node_modules
install:
  - yarn global add codecov
  - yarn
script:
  - lint-staged
  - yarn run test:ci && codecov
deploy:
  provider: releases
  api_key: $GH_TOKEN
  file_glob: true
  file: "dist/*/**"
  skip_cleanup: true
  on:
    tags: true
    all_branches: true
